Feature: 닉네임 중복 확인하는 API 구현
Kernel360/f1-JDON-Backend pull request #144
Opened 2024-01-15 09:09 UTC by anso33

## 개요

### 요약

### 변경한 부분
- `POST` `/api/v1/nickname/duplicate` 구현
- 닉네임이 중복된 닉네임인지 확인하는 API 구현했습니다. 
- 본인 닉네임과 같은 닉네임이면 이미 해당 닉네임이라는 에러를, 다른 유저가 사용중인 닉네임이면 이미 존재하는 닉네임이라는 에러를 반환합니다. 

### 변경한 결과
<img width="1349" alt="image" src="https://github.com/Kernel360/f1-JDON-Backend/assets/68376744/f93b6b94-afcb-46a0-bf41-ca1fe14142ab">

![image](https://github.com/Kernel360/f1-JDON-Backend/assets/68376744/0d7608a7-48b6-4e56-90ce-c33c327b2264)

![image](https://github.com/Kernel360/f1-JDON-Backend/assets/68376744/a0cf2832-978e-4ba5-8367-b61af0c9a8a4)

![image](https://github.com/Kernel360/f1-JDON-Backend/assets/68376744/9da30db5-1aa3-4dfd-b941-9ee09a2929aa)

### 이슈

- closes: #142 

---

## PR 유형

어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경, 주석 변경)
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 파일 혹은 폴더명 수정, 삭제
- [ ] 배포 관련

2024-01-16 03:07 UTC, anso33 commented on module-api/src/main/java/kernel/jdon/member/service/MemberService.java
> +		Member existNicknameMember = memberRepository.findByNickname(nickname);
exist로 수정하기

2024-01-16 11:20 UTC, aqrms commented on module-common/src/main/java/kernel/jdon/error/code/api/MemberErrorCode.java
> +	CONFLICT_SAME_NICKNAME(HttpStatus.CONFLICT, "기존 닉네임과 동일합니다.");
그럼 얘는 이제 안쓰인다면 삭제해도 좋을 것 같습니다!

2024-01-16 12:46 UTC, aacara requested changes
고생하셨습니다~!

2024-01-16 12:46 UTC, aacara commented on module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
>  		return ResponseEntity.noContent().build();
정말 궁금해서 질문드립니다!
만약에 아무런 응답도 반환하지 않으면 
클라이언트에서 닉네임이 사용 여부를 어떻게 알 수 있는지 궁금합니다.

2024-01-16 12:46 UTC, aacara commented on module-api/src/main/java/kernel/jdon/member/service/MemberService.java
>  				.member(member)
```code
List<Skill> findSkillList = skillIdList.stream()
			.map(skillId -> skillRepository.findById(skillId)
				.orElseThrow(() -> new ApiException(MemberErrorCode.NOT_FOUND_SKILL))).toList();
```
여기서 skillId를 하나씩 가져오는 대신 
skillRepository.findAllById(skillIdList);로 한번에 조회로 가져오면 
통신 횟수가 감소할 것 같은데 어떻게 생각하시나요?

2024-01-16 12:46 UTC, aacara commented on module-api/src/main/java/kernel/jdon/member/service/MemberService.java
```code
RegisterMemberDto registerMemberDto = RegisterMemberDto.builder()
			.email(userInfo.get("email"))
			.jobCategory(findJobCategory)
			.memberRole(MemberRole.ROLE_USER)
			.socialProvider(SocialProviderType.ofType(userInfo.get("provider")))
			.build();
```
이 부분을 dto 안에 of 메소드 안에 넣어주면 어떨까요?

2024-01-16 12:48 UTC, yoonseon12 commented on module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
>  		return ResponseEntity.noContent().build();
프론트엔드에서 api 요청 시 응답코드가 2XX번 이라면 정상인 것으로 식별할 수 있습니다 ☝️

2024-01-16 12:54 UTC, yoonseon12 commented on module-api/src/main/java/kernel/jdon/member/service/MemberService.java
>  				.member(member)
질문이 이해가 잘 안됩니다.

2024-01-16 12:58 UTC, aacara commented on module-api/src/main/java/kernel/jdon/member/service/MemberService.java
>  				.member(member)
skillRepository.findById(skillId)를 여러번 호출하는 대신
skillRepository.findAllById(skillIdList);로 한번의 조회로 모든 데이터를 가져온다면
데이터베이스와의 통신 횟수가 줄어들 것 같다고 생각했습니다

2024-01-16 13:09 UTC, aacara approved these changes

2024-01-17 01:50 UTC, anso33 commented on module-api/src/main/java/kernel/jdon/member/service/MemberService.java
>  				.member(member)
쿼리count가 줄어들긴하지만 속도에 별 차이가 없고, 예외를 어떻게 처리할 것인가에 대해 다같이 다시 논의해보기로 했습니다!

2024-01-17 01:51 UTC, aqrms approved these changes
고생하셨습니다!

2024-01-17 01:51 UTC, merged