Feature: 커피챗 신청 API
Kernel360/f1-JDON-Backend pull request #198
Opened 2024-01-25 10:43 UTC by aqrms

### 요약

커피챗 신청 API를 구현했습니다
- 커피챗 엔터티가 신청로직에 대한 책임을 지도록 했습니다
  - CoffeeChatMember 레포지토리를 두지않고 CoffeeChat에서만 신청여부를 관리합니다

### 변경한 부분

- CoffeeChatRepository
  -  신청가능한 커피챗을 찾아오도록 쿼리메소드를 추가했습니다
- CoffeeChatErrorCode
  - 예외 상황에 따른 에러코드를 추가했습니다 
- CoffeeChatService
  - apply 메서드에서 db에서 신청하고자 하는 엔터티를 찾아올 때 상태 칼럼이 OPEN인지 확인하고 결과가 없으면 예외를 던지도록 했습니다. 
  - 커피챗 상태와 삭제여부 상태를 구분하기 위해 findById 공통 메서드를 'findExist~'로 변경했습니다.
  - 커피챗을 개설한 host가 guest로서 참여신청을 하는 경우 예외를 던집니다.
- CoffeeChatEntity
  - coffeeChat 엔터티가 신청에 대한 책임을 갖도록 했습니다.
  - coffeeChatMemberList에 cascade.ALL, orphanRemoval 옵션을  적용해서
  coffeeChat만 변경되어도 coffeeChatMember에도 변경사항이 반영되도록 했습니다. 
  - updateStatusByRecruitCount 메소드를 재활용해서 참여인원에 따라 상태를 변경합니다.
- CoffeeChatMember
  - 연결 엔터티 생성을 위해 정적 팩토리 메서드를 추가 했습니다

### 변경한 결과

- 아래와 같이 status가 open인 커피챗에 참여신청을 하면
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/111513287/e139b04a-5532-4062-9657-6feafe4d1dc8)
- currentRecruitCount가 올라가고 totalRecruitCount와 같으면 Status가 업데이트 됩니다
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/111513287/0a9fd8e2-b128-431d-a23b-c0987ed104a0)
- Status가 OPEN이 아닌 해당 커피챗에 또 참여신청을 하면 아래와 같이 예외를 반환합니다.
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/111513287/228c6cb8-d8a6-48a7-b61e-eeb33c5fbdc2)
- 본인이 작성한 커피챗에 참여신청을 하면 예외를 반환합니다.
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/111513287/ac99bfd0-4426-4e0c-9937-e4ae03eaa5fb)

### 이슈

- closes: #186 

---

## PR 유형

어떤 변경 사항이 있나요?

- [X] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경, 주석 변경)
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 파일 혹은 폴더명 수정, 삭제
- [ ] 배포 관련

2024-01-26 05:24 UTC, aqrms commented on module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
> +		return coffeeChatRepository.findByIdAndCoffeeChatStatus(coffeeChatId, CoffeeChatActiveStatus.OPEN)
존재랑 상태검사를 분리

2024-01-26 05:32 UTC, aqrms commented on module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
> +	private Member findExistMember(Long memberId) {
findMember로 수정해도 될것 같다 탈퇴한 사용자를 찾아올 수 있기때문에
그렇다고 멤버의 삭제여부 칼럼을 조회조건으로 줄 필요는 없을 것 같다
탈퇴한 사용자의 세션키를 위조해서 요청이 올 수 없기때문에(세션키는 로그인 사용자에게 서버가 만들어서 주니까)

2024-01-26 05:35 UTC, aqrms commented on module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
> +			throw new ApiException(CoffeeChatErrorCode.CAN_NOT_JOIN_OWN_COFEECHAT);
cofee 오타

2024-01-26 05:36 UTC, yoonseon12 commented on module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
> +			throw new ApiException(CoffeeChatErrorCode.CAN_NOT_JOIN_OWN_COFEECHAT);
CAN_NOT_JOIN_OWN_COFEECHAT 오타가 있습니다 !!
CAN_NOT_JOIN_OWN_COFFEECHAT

2024-01-26 05:36 UTC, aqrms commented on module-domain/src/main/java/kernel/jdon/coffeechatmember/domain/CoffeeChatMember.java
> +	public static CoffeeChatMember from(Member member, CoffeeChat coffeeChat) {
이걸 쓰지 않고 빌더 사용

2024-01-26 05:39 UTC, anso33 commented on module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
> +			.orElseThrow(() -> new ApiException(MemberErrorCode.NOT_FOUND_MEMBER));
사용한 repository method 상 findMember라는 메서드 명이 더 명확할 것 같아요
WithDraw라는 Status를 가진 탈퇴회원이 이 메서드를 총해서  조회될 수 있을 것 같습니다.

2024-01-26 05:39 UTC, anso33 commented on module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
> +		this.coffeeChatMemberList.add(coffeeChatMember);
이 엔티티의 경우 cascade를 활용할지, 중간 테이블의 repository를 사용할지 같이 고민해봅시다.

2024-01-26 06:42 UTC, aacara requested changes
고생하셨습니다~!
확인 부탁드립니다

2024-01-29 03:05 UTC, aqrms commented on module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
> +			.orElseThrow(() -> new ApiException(MemberErrorCode.NOT_FOUND_MEMBER));
memberId는 세션에서 로그인한 사용자의 정보에서 받아오기에 탈퇴 사용자가 조회될 가능성은 없을 것 같습니다!
탈퇴한 사용자의 세션키를 위조해서 요청이 올 수 없기때문에(세션키는 로그인 사용자에게 서버가 만들어서 주니까)

2024-01-29 06:35 UTC, aqrms commented on module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
> +		CoffeeChatMember coffeeChatMember = CoffeeChatMember.from(findMember, findCoffeeChat);
빌더로 변경했습니다

2024-01-29 06:39 UTC, yoonseon12 commented on module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
> +		this.currentRecruitCount += 1;
`this.currentRecruitCount++;` 은 어떤가요?

2024-01-29 06:43 UTC, yoonseon12 approved these changes

2024-01-29 07:45 UTC, aacara reviewed
고생하셨습니다~!

2024-01-29 07:45 UTC, aacara commented on module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
> +	private void checkIfGuestEqualToHost(Member findMember, CoffeeChat findCoffeeChat) {
매개변수가 member인 것을 고려하면
 `checkIfGuestEqualToHost` -> `checkIfMemberIsHost`로 바꾸는 건 어떠신가요?
 
Guest랑 Host는 배타적인 개념인 것 같습니다!

2024-01-29 07:47 UTC, aacara reviewed
고생하셨습니다~! 
리뷰 남겼습니다!

2024-01-29 07:49 UTC, aacara approved these changes
고생하셨습니다~!
리뷰 남겨드렸습니다!

2024-01-30 01:37 UTC, anso33 approved these changes
고생하셨습니다.

2024-01-30 01:42 UTC, merged