Fix: 기술스택 연관어 목록으로 검색하도록 수정
Kernel360/f1-JDON-Backend pull request #461
Opened 2024-03-14 02:01 UTC by yoonseon12

## 개요

### 요약
메인화면 및 JD 목록에서 기술스택 기반으로 검색할 때, 연관어로 검색한다면 해당 연관어를 포함하고있는 기술스택 목록을 조회할 수 있도록 수정했습니다.

### 변경한 부분
- 연관어 목록을 가져오는 객체를 호출하는 부분을 infrastructor 계층이 아닌 domain 계층에서 호출하도록 변경했습니다.
  - 연관어를 검색했을 경우 domain 계층에서 해당 연관어를 포함하고있는 origin 기술스택 목록을 가져오고 이를 infrastructor 계층으로 전달하여 SQL 질의를 통해 해당 연관어를 포함하고 있는 기술스택 목록을 기반으로 데이터를 가져오도록 변경했습니다.
- serviceImpl에 호출하는 메서드가 추가됨에 따라 테스트 코드에 추가된 메서드를 mocking하는 코드를 추가했습니다. 

### 변경한 결과
### 테스트 실행결과
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/52c80933-0209-45df-aacb-7eae89be7aec)
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/71e9a146-9b86-4176-9e37-856767a21cd6)

### 메인화면 기술스택 기반 데이터 조회
#### 같은 연관어를 포함하고 있는 기술스택 목록 기반 조회
<img width="783" alt="image" src="https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/44fab559-f74d-46c3-bbd4-8bbfdf315363">

![image](https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/a28dd0e7-c85e-40e6-96da-1e1eef6f7202)
연관어 `언어`를 포함하고 있는 기술스택의 목록을 기반으로 검색합니다.

#### 단일 연관어를 포함하고 있는 기술스택 목록 기반 조회
<img width="763" alt="image" src="https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/08106a83-c813-41ec-860f-403eed91600f">

![image](https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/44079ae7-c6a4-4d3d-9801-de16000a7771)
연관어 `자바`를 포함하고 있는 기술스택 기반으로 검색합니다.

### JD 목록 조회
#### 같은 연관어를 포함하고 있는 기술스택 목록 기반 조회
<img width="564" alt="image" src="https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/4703176c-d608-486c-aae1-4614b066c592">

![image](https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/33587fbd-3015-4067-81d6-dab9e6bbcc02)
연관어 `언어`를 포함하고 있는 기술스택의 목록을 기반으로 검색합니다.

#### 단일 연관어를 포함하고 있는 기술스택 목록 기반 조회
<img width="544" alt="image" src="https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/eb89368b-6042-443c-b75e-c1dd970b42ce">

![image](https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/f886c4cd-46a7-4a1b-a886-ccbf7aa02575)
연관어 `고`를 포함하고 있는 기술스택 기반으로 검색합니다.

### 이슈

- closes: #460 

---

## PR 유형

어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경, 주석 변경)
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 파일 혹은 폴더명 수정, 삭제
- [ ] 배포 관련

2024-03-14 05:15 UTC, aacara requested changes
LGTM, 회의로 함께 코드리뷰 진행했습니다~

2024-03-14 05:15 UTC, aacara commented on module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
>              .limit(inflearnLectureCount)
이 부분에도
`.orderBy(Expressions.numberTemplate(Double.class, "function('rand')").asc())`를 추가한다면
언어를 검색했을 때, 가장 상단의 언어를 늘 반환하기보다
다양한 언어의 강의가 추천 결과로 나올 것 같습니다~

2024-03-14 05:15 UTC, aacara commented on module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImplTest.java
> +        given(jdReader.findWantedJdList(mockPageInfoRequest, mockJdCondition, mockOriginSkillKeywordList))
테스트 map으로 바로 가져오는 것보다 Reader로 가져오는게
테스트 시 모킹처리하기에 좋은 코드라는 점 확인했습니다~

2024-03-14 08:07 UTC, aqrms approved these changes
아래의 흐름으로 이해했습니다. 고생하셨습니다!
1. 유저가 입력한 검색어의 연관검색어를 SkillKeyword 테이블에서 모두 찾아 list로 들고온다
2. 해당 연관검색어(연결엔터티)에서 Skill의 origin keyword를 뽑아 list로 만든다.
3. 그 originKeywordList를 인프런강의,원티드JD 검색시 in 절 조건으로 주어 검색한다

2024-03-15 06:17 UTC, anso33 approved these changes
고생하셨습니다~

2024-03-15 06:22 UTC, aacara approved these changes
LGTM, 고생하셨습니다~

2024-03-15 06:22 UTC, merged