add dummy data api for favorite inflearn lecture api
Kernel360/f1-JDON-Backend pull request #94
Opened 2024-01-05 14:20 UTC by aacara

## 개요

### 요약
- 가데이터를 반환하는 Skill 관련 API 구현

### 변경한 부분
- 프론트엔드 요청에 따라 API 명세서 규격에 맞는 요청받고 데이터를 응답하도록 API를 구현하였습니다.
  - 내가 찜한 영상 목록 조회하기 API : https://www.notion.so/a54d5635404a4dfd8b79d7561e5b80d6
  - 영상 찜하는 버튼 누르기 API : https://www.notion.so/API-d0b2b8e78dd142ca8ace674e8d4a5705

### 변경한 결과
#### 내가 찜한 영상 목록 조회하기 API
- /api/v1/favorites
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/86637372/c44905d4-0b10-4ee1-83ad-df54d17f9ba4)
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/86637372/a800ea80-22c5-401c-84d9-5991b99ae663)

#### 영상 찜하는 버튼 누르기 API
- /api/v1/favorites
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/86637372/7995a334-2a42-452c-b9a5-2450b73c57ce)
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/86637372/650b7723-164a-4973-85bc-7b68e69ab915)

### 이슈

- closes: #69 

---

## PR 유형

어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경, 주석 변경)
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 파일 혹은 폴더명 수정, 삭제
- [ ] 배포 관련

2024-01-06 08:03 UTC, yoonseon12 requested changes

2024-01-06 08:03 UTC, yoonseon12 commented on module-domain/src/main/java/kernel/jdon/favorite/domain/dto/request/SaveFavoriteRequest.java
> +public class SaveFavoriteRequest {
사전에 정의한 컨벤션에 맞도록 Save -> Create로 클래스명 변경이 필요합니다.

2024-01-08 01:27 UTC, aacara commented on module-domain/src/main/java/kernel/jdon/favorite/domain/dto/request/SaveFavoriteRequest.java
> +public class SaveFavoriteRequest {
넵, 반영하였습니다

2024-01-08 01:49 UTC, anso33 reviewed
질문 코멘트 남겼슴다

2024-01-08 01:49 UTC, anso33 commented on module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java
> +	}
이것도 좋아요 등록이긴하니까 
> 저희 코드컨벤션에서 정의했던 것 처럼 등록 메서드는 URI 객체를 반환하여 응답 헤더에 넣도록 수정하는게 좋을 것 같아요.

이 컨벤션을 따라야하지 않을까요?? 흠.. 어떻게 생각하시나유...

2024-01-08 02:12 UTC, aacara commented on module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java
> +	}
올리기 전에 코딩 컨벤션 한번 더 확인해야겠습니다! 반영했습니다~

2024-01-08 02:26 UTC, yoonseon12 commented on module-domain/src/main/java/kernel/jdon/favorite/domain/dto/response/CreateFavoriteResponse.java
> +@AllArgsConstructor
구현하는 입장에서 이 클래스를 인스턴스화할 일이 없으면 private 생성자를 두는 것이 어떤가요 ?

2024-01-08 02:42 UTC, aacara commented on module-domain/src/main/java/kernel/jdon/favorite/domain/dto/response/CreateFavoriteResponse.java
> +@AllArgsConstructor
넵, 반영했습니다~

2024-01-08 02:56 UTC, yoonseon12 approved these changes
수고하셨습니다.

2024-01-08 05:20 UTC, anso33 approved these changes
고생하셨습니당!!!!!!!!!!!!

2024-01-08 05:20 UTC, aqrms approved these changes
LGTM

2024-01-08 05:23 UTC, merged